export const STATUS_CODES = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
};

export const RESPONSE_MESSAGES = {
  AUTH: {
    SUCCESS: "Login successful.",
    FAILED: "Invalid credentials.",
    UNAUTHORIZED: "Access denied.",
    DUPLICATE_EMAIL: "An account with this email already exists.",
    REGISTRATION_SUCCESS: "Registration successful. Verification code sent.",
    OTP_SENT:
      "If an account exists for this email, a verification code has been sent.",
    VERIFICATION_SUCCESS: "Verification successful.",
    VERIFICATION_CODE_SENT: "A new verification code has been sent.",
    LOGOUT_SUCCESS: "Logged out successfully.",
    INVALID_OR_EXPIRED_VERIFICATION_CODE:
      "Invalid or expired verification code.",
    VERIFICATION_CODE_ALREADY_USED: "Verification code has already been used.",
    VERIFICATION_CODE_EXPIRED: "Verification code has expired.",
    TOO_MANY_VERIFICATION_ATTEMPTS: "Too many verification attempts.",
    VERIFICATION_FAILED: "Unable to verify account.",
    INVALID_REFRESH_TOKEN: "Invalid refresh token.",
    INVALID_VERIFICATION_REQUEST: "Invalid verification request.",
    VERIFICATION_CODE_REQUEST_TOO_SOON:
      "Please wait before requesting another verification code.",
      ADMIN_ACCESS_GRANTED: "Admin access granted.",
  },
  GLOBAL: {
    SERVER_ERROR: "Something went wrong. Please try again later.",
    NOT_FOUND: "Resource not found.",
  },
  VALIDATION: {
    NAME_MIN: "Name must be at least 2 characters",
    NAME_MAX: "Name must not exceed 100 characters",
    EMAIL_INVALID: "Invalid email address",
    PASSWORD_MIN: "Password must be at least 8 characters",
    PASSWORD_REQUIRED: "Password is required",
    PASSWORD_MAX: "Password must not exceed 128 characters",
    AUTHENTICATION_REQUIRED: "Authentication required.",
    INTERNAL_SERVER_ERROR: "Internal server error.",
    INVALID_AUTHENTICATION: "Invalid authentication.",
    INVALID_OR_EXPIRED_TOKEN: "Invalid or expired access token.",
    TOO_MANY_REQUESTS: "Too many requests. Please try again later.",
    TOO_MANY_VERIFICATION_ATTEMPTS:
      "Too many verification attempts. Please try again later.",
    TOO_MANY_OTP_REQUESTS: "Too many OTP requests. Please try again later.",
    NAME_MIN: "Name must be at least 2 characters",
    NAME_MAX: "Name must not exceed 100 characters",
    EMAIL_INVALID: "Invalid email address",
    PASSWORD_MIN: "Password must be at least 8 characters",
    PASSWORD_REQUIRED: "Password is required",
    PASSWORD_MAX: "Password must not exceed 128 characters",
    CHALLENGE_ID_REQUIRED: "Challenge ID is required",
    OTP_INVALID: "OTP must be exactly 6 digits",
    REFRESH_TOKEN_REQUIRED: "Refresh token is required",
  },
};
